services:
  wordpress:
    image: ona-wordpress:6.0.1-php8.1
    build:
      context: https://gitlab.com/ona-ar/wordpress-dockerfile.git
      args:
        WP_IMAGE_TAG: 6.0.1-php8.1
    container_name: portfolio-wordpress
    hostname: wordpress
    domainname: localhost
    restart: "no"
    depends_on:
      - mysql
    ports:
      - 3000:80
    expose:
      - 9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APACHE_RUN_USER: ona
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: banana
      WORDPRESS_DB_PASSWORD: banana
      WORDPRESS_DB_NAME: banana
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_DISPLAY', false);
        define('FS_METHOD', 'direct');
    working_dir: /var/www/html
    volumes:
      - ./docker-volumes/plugins:/var/www/html/wp-content/plugins:rw
      - ./docker-volumes/uploads:/var/www/html/wp-content/uploads:rw
      - ./src:/var/www/html/wp-content/themes/dev-theme
      - ./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini:ro
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  mysql:
    container_name: portfolio-mysql
    image: mysql:5.7
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    volumes:
      - ./docker-volumes/db-data:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: banana
      MYSQL_DATABASE: banana
      MYSQL_USER: banana
      MYSQL_PASSWORD: banana